eureka:
  client:
    serviceUrl:
      #实现注册中心的高可用
      defaultZone: http://peer2:8761/eureka/,http://peer1:8762/eureka/
spring:
  application:
    name: front-server
server:
  port: 8083
#配置断路器超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000

#使用feign开启hystrix 必须要添加此配置
feign:
  hystrix:
    enabled: true